#!/bin/sh

### BEGIN INIT INFO
# Provides: shnopp
# Required-Start: 
# Required-Stop: 
# Should-Start: 
# Should-Stop: 
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: shnopp
# Description: shnopp
### END INIT INFO

mkdir -p /var/run/shnopp/
chown osmc:osmc /var/run/shnopp/ -R
sudo python /home/osmc/shnopp/shnopp.py "$@"
